version: 0.2

phases:

  build:
    commands:
      - echo Build started on `date`
      - env
      - composer install --no-progress --no-suggest

  post_build:
    commands:
      - echo Build completed on `date`
      - ./vendor/bin/phpunit tests
cache:
  paths:
    # Composer cache:
    - /root/.composer/**/*
