version: "3.1"
services:
  # Local dynamodb
  dynamodb-local:
    command: "-jar DynamoDBLocal.jar  -inMemory "
    image: "amazon/dynamodb-local:latest"

  # Create the Dynamodb tables
  dynamodb-create-tables:
    environment: 
      DYNAMODB_ENDPOINT: http://dynamodb-local:8000 # use our local dynamodb
      AWS_ACCESS_KEY_ID: 'DUMMYIDEXAMPLE'
      AWS_SECRET_ACCESS_KEY: 'DUMMYEXAMPLEKEY'
      AWS_REGION: 'eu-west-1'
    depends_on:
      - dynamodb-local
    image: "amazon/aws-cli:latest"
    command: dynamodb create-table --table-name php-sessions --attribute-definitions AttributeName=id,AttributeType=S --key-schema AttributeName=id,KeyType=HASH  --provisioned-throughput ReadCapacityUnits=5,WriteCapacityUnits=5 --endpoint-url=http://dynamodb-local:8000

  # A PHP container we can test in 
  php:
    depends_on:
      - dynamodb-create-tables
    build: .
    environment: 
      SESSION_TABLE: php-sessions
      DYNAMODB_ENDPOINT: http://dynamodb-local:8000 # use our local dynamodb
      AWS_ACCESS_KEY_ID: 'DUMMYIDEXAMPLE'
      AWS_SECRET_ACCESS_KEY: 'DUMMYEXAMPLEKEY'
      AWS_REGION: 'eu-west-1'
    volumes:
      - ..:/var/www/html
    working_dir: /var/www/html
    
 
  # A PHP container we can test in 
  php5:
    depends_on:
      - dynamodb-create-tables
    image: php:5-cli
    environment: 
      SESSION_TABLE: php-sessions
      DYNAMODB_ENDPOINT: http://dynamodb-local:8000 # use our local dynamodb
      AWS_ACCESS_KEY_ID: 'DUMMYIDEXAMPLE'
      AWS_SECRET_ACCESS_KEY: 'DUMMYEXAMPLEKEY'
      AWS_REGION: 'eu-west-1'
    volumes:
      - ..:/var/www/html
    working_dir: /var/www/html
    
  php8:
    depends_on:
      - dynamodb-create-tables
    image: php:8-cli
    environment: 
      SESSION_TABLE: php-sessions
      DYNAMODB_ENDPOINT: http://dynamodb-local:8000 # use our local dynamodb
      AWS_ACCESS_KEY_ID: 'DUMMYIDEXAMPLE'
      AWS_SECRET_ACCESS_KEY: 'DUMMYEXAMPLEKEY'
      AWS_REGION: 'eu-west-1'
    volumes:
      - ..:/var/www/html
    working_dir: /var/www/html


  php8.1:
    depends_on:
      - dynamodb-create-tables
    image: php:8.1-cli
    environment: 
      SESSION_TABLE: php-sessions
      DYNAMODB_ENDPOINT: http://dynamodb-local:8000 # use our local dynamodb
      AWS_ACCESS_KEY_ID: 'DUMMYIDEXAMPLE'
      AWS_SECRET_ACCESS_KEY: 'DUMMYEXAMPLEKEY'
      AWS_REGION: 'eu-west-1'
    volumes:
      - ..:/var/www/html
    working_dir: /var/www/html

  php7.1:
    depends_on:
      - dynamodb-create-tables
    image: php:7.1-cli
    environment: 
      SESSION_TABLE: php-sessions
      DYNAMODB_ENDPOINT: http://dynamodb-local:8000 # use our local dynamodb
      AWS_ACCESS_KEY_ID: 'DUMMYIDEXAMPLE'
      AWS_SECRET_ACCESS_KEY: 'DUMMYEXAMPLEKEY'
      AWS_REGION: 'eu-west-1'
    volumes:
      - ..:/var/www/html
    working_dir: /var/www/html

  php7.2:
    depends_on:
      - dynamodb-create-tables
    image: php:7.2-cli
    environment: 
      SESSION_TABLE: php-sessions
      DYNAMODB_ENDPOINT: http://dynamodb-local:8000 # use our local dynamodb
      AWS_ACCESS_KEY_ID: 'DUMMYIDEXAMPLE'
      AWS_SECRET_ACCESS_KEY: 'DUMMYEXAMPLEKEY'
      AWS_REGION: 'eu-west-1'
    volumes:
      - ..:/var/www/html
    working_dir: /var/www/html

  php7.3:
    depends_on:
      - dynamodb-create-tables
    image: php:7.1-cli
    environment: 
      SESSION_TABLE: php-sessions
      DYNAMODB_ENDPOINT: http://dynamodb-local:8000 # use our local dynamodb
      AWS_ACCESS_KEY_ID: 'DUMMYIDEXAMPLE'
      AWS_SECRET_ACCESS_KEY: 'DUMMYEXAMPLEKEY'
      AWS_REGION: 'eu-west-1'
    volumes:
      - ..:/var/www/html
    working_dir: /var/www/html

  php7.4:
    depends_on:
      - dynamodb-create-tables
    image: php:7.1-cli
    environment: 
      SESSION_TABLE: php-sessions
      DYNAMODB_ENDPOINT: http://dynamodb-local:8000 # use our local dynamodb
      AWS_ACCESS_KEY_ID: 'DUMMYIDEXAMPLE'
      AWS_SECRET_ACCESS_KEY: 'DUMMYEXAMPLEKEY'
      AWS_REGION: 'eu-west-1'
    volumes:
      - ..:/var/www/html
    working_dir: /var/www/html