#!/bin/bash
pecl install xdebug 
docker-php-ext-enable xdebug
 { \
            echo "xdebug.mode=debug"; \
            echo "xdebug.start_with_request=yes"; \
            echo "xdebug.client_host=host.docker.internal"; \
        } > /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini; 