#!/bin/bash
DIR="$( cd "$( dirname "$(realpath "${BASH_SOURCE[0]}")" )" >/dev/null 2>&1 && pwd )"
cd $DIR
docker-compose up -d
echo "Running composer-install"
docker-compose run php composer install --no-progress --no-suggest
