
name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
            
    - name: Setup test environment
      run: ./tools/setup

    # Run the tests inside the docker image
    - name: Run unit tests
      run: ./tools/test-all-php-versions
